version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: visual_search_backend
    ports:
      - "8000:8000"
    volumes:
      # Wir binden den data-Ordner als Volume ein.
      # Dadurch müssen GB-große Bilddateien nicht ins Docker-Image gebaut werden!
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: visual_search_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped